### PR TITLE
Python 2 version of the same file.

### PR DESCRIPTION
**Pull request by innocent-rajan**

### CODE REVIEW

**Comment by christianbender** [comment]
@innocent-rajan 
I get this error message with python 2:  
>  Traceback (most recent call last):
  File "DijkstraV2.py", line 87, in <module>
    print Dijkstra(G,'s')
  File "DijkstraV2.py", line 43, in Dijkstra
    Q = priorityDictionary()  # estimated distances of non-final vertices
NameError: global name 'priorityDictionary' is not defined

I have seen this error occurred in the origin file, too.

**Comment by christianbender** [comment]
@innocent-rajan 
The problem is the call of the constructor ```priorityDictionary() ```. Because this constructor isn't define.

**Comment by christianbender** [comment]
@Thuva4 Have you an idea to fix this problem? See my comments above.

**Comment by Thuva4** [comment]
Thank for pointing this out 👍 They forget to add the priorityDictionary class/file. Close this MR and we can add the priorityDictionary.

**Comment by christianbender** [comment]
@Thuva4 I closed the PR

**Pull request closed without merging**
